name: run-tests
on: [workflow_call]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Actions
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: |
          pip install semgrep
          semgrep --version

      - name: Run Tests
        run: semgrep scan --error --config auto
