name: test_workflow
on:
  pull_request:

  push:
    branches:
      '**'
jobs:
  sast:
    uses: SmartDCSITlimited/actions-store/.github/workflows/SAST.yml@main
  secret-detection:
    uses: SmartDCSITlimited/actions-store/.github/workflows/SecretDetection.yml@main
  python-linting:
    uses: SmartDCSITlimited/actions-store/.github/workflows/PythonLinting.yml@main

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Requirements
        run: |
          pip install --upgrade pip

          pip install pytest
          pytest --version

          pip install -r requirements.txt

      - name: Run Tests
        run: |
          export PYTHONPATH=/workspaces/test-event-generator:$PYTHONPATH
          pytest
